use_frameworks!

platform :ios, '10.0'

target 'DLSectionLayout_Example' do
  pod 'DLSectionLayout', :path => '../'

  target 'DLSectionLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
